name: Pre-release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true

jobs:
  pre-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Update version in pyproject.toml
        run: |
          # Install toml manipulation tool
          uv pip install toml-cli
          
          # Update version
          toml set pyproject.toml project.version "${{ github.event.inputs.version }}" > temp.toml && mv temp.toml pyproject.toml
          
          # Verify the update
          cat pyproject.toml | grep -A 2 version

      - name: Create pre-release packages
        run: |
          # Create release assets directory
          mkdir -p release-assets

          # Create pre-release packages for different platforms and AI agents
          bash .github/workflows/scripts/create-release-packages.sh "${{ github.event.inputs.version }}" "$GITHUB_WORKSPACE/release-assets"

      - name: Build package
        run: |
          uv pip install build
          python -m build

      - name: Create Pre-release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: "v${{ github.event.inputs.version }}"
          name: "Pre-release v${{ github.event.inputs.version }}"
          draft: false
          prerelease: true
          artifacts: "dist/*,release-assets/*"
          body: |
            ## Pre-release v${{ github.event.inputs.version }}

            This is a pre-release of Full Kit CLI v${{ github.event.inputs.version }}.

            ### What's included
            - Full Kit CLI with Goal-Driven, Blueprint-Driven, and Spec-Driven Development
            - Support for all major AI agents (Claude, Gemini, Copilot, Cursor, Qwen, etc.)
            - Template packages for initializing projects with any AI agent
            - Full integration between all three methodologies

            ### How to use
            ```bash
            uvx fullkit-cli init my-project
            # or install globally
            uv tool install fullkit-cli
            fullkit init my-project
            ```

            ⚠️ **This is a pre-release version - use with caution in production environments.**